language: node_js
node_js:
  - "13"
install:
  - yarn install
  - yarn global add codecov
jobs:
  include:
    - stage: Unit Tests
      script: yarn test:unit --coverage && codecov
    - stage: Lint
      script: yarn lint
    - stage: Deploy GitHub Pages
      script: yarn docs:build
      deploy:
        on:
          branch: master
        provider: pages
        skip-cleanup: true
        local_dir: docs/.vuepress/dist
        github-token: $GITHUB_TOKEN
        repo: dm4t2/vue-currency-input
    - stage: Publish npm package
      script: yarn build
      deploy:
        edge: true
        on:
          branch: master
          tags: true
        provider: npm
        skip_cleanup: true
        email: dm4t2@outlook.com
        api_key:
          secure: MmWLoUUEtzy6p0zarAZmvpUOcBBFVz9CLqL5HJ+l/rQUCj3aCi6MWKA82OvKgmRh+SEAKr3vDFJVKYwGD+mHHylJe7XwNYCAM3Pxru+RIi2qjbdIU85U07iNsZxsoeSm19aVmu1aQUPMnVqwX5P0oonFi1AQi2ulj7Vt5f9T9owb+xVpNpHrMxAMc4qUZmnvLuEepyM2kPAYYHFA8KYkVcUkQxB8wn3yVUyKShWJkcTDoaS6GXzY3wAd29HEAtNMpsN7xbwCkrv7348qv3+tgV6LvPWYQTD/c/dnHcyR4omlj33cn/nVYHwEkfJOdtuFEjTAHkwaXeFOb7kl4UnXE+u+DjhH5n3Cguy/IIaREdDjW2OtJAe6gTK1nAo+u8yk+r7RxDqAfc/Y1bzBKnsNbVfK6R9lR3ufNqetDbL+lVZLP7WuCI5MwT0l/sl3G83JKIqfe54LI9E9VD2TY31HV18YHKlxDCy8rKxzke49sLhqxBRdkwOZGTmaFcGdtUMXVN/aL1EFjaO8w3hoy9b1h8FVKlW2f4gJ2uloPuXXgraSsZ2HboA3jHEWxjD0A3dNxmqNBIHIpmbmSaDvoj/ibPMrbh1FiJUxkYneGy1XLaXeSxVHs9tQkVxxZqHsEPyEich7vVdd/Bnh9pbJ//WIFKjZViQgh43aSHNY04d7cls=
